version: '3'
services:
  evaluate-app:
    build:
      context: .
      dockerfile: Dockerfile.evaluate-app
    ports:
      - "50051:50051" # Map the server port from the container to the host
    networks:
      - grpc-network

  web-app:
    build:
      context: .
      dockerfile: Dockerfile.web-app
    depends_on:
      - evaluate-app
    networks:
      - grpc-network
    

networks:
  grpc-network:
