# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: communication.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x63ommunication.proto\"/\n\x0e\x46ormulaRequest\x12\x0f\n\x07\x66ormula\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\"!\n\x0f\x46ormulaResponse\x12\x0e\n\x06result\x18\x01 \x01(\t2H\n\x10\x46ormulaEvaluator\x12\x34\n\x0f\x45valuateFormula\x12\x0f.FormulaRequest\x1a\x10.FormulaResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'communication_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_FORMULAREQUEST']._serialized_start=23
  _globals['_FORMULAREQUEST']._serialized_end=70
  _globals['_FORMULARESPONSE']._serialized_start=72
  _globals['_FORMULARESPONSE']._serialized_end=105
  _globals['_FORMULAEVALUATOR']._serialized_start=107
  _globals['_FORMULAEVALUATOR']._serialized_end=179
# @@protoc_insertion_point(module_scope)
