# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import communication_pb2 as communication__pb2


class FormulaEvaluatorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EvaluateFormula = channel.unary_unary(
                '/FormulaEvaluator/EvaluateFormula',
                request_serializer=communication__pb2.FormulaRequest.SerializeToString,
                response_deserializer=communication__pb2.FormulaResponse.FromString,
                )


class FormulaEvaluatorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def EvaluateFormula(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FormulaEvaluatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EvaluateFormula': grpc.unary_unary_rpc_method_handler(
                    servicer.EvaluateFormula,
                    request_deserializer=communication__pb2.FormulaRequest.FromString,
                    response_serializer=communication__pb2.FormulaResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'FormulaEvaluator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class FormulaEvaluator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def EvaluateFormula(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/FormulaEvaluator/EvaluateFormula',
            communication__pb2.FormulaRequest.SerializeToString,
            communication__pb2.FormulaResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
